[2022-12-04 17:03:46,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task manual__2022-12-04T17:03:42.767246+00:00 [queued]>
[2022-12-04 17:03:46,674] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task manual__2022-12-04T17:03:42.767246+00:00 [queued]>
[2022-12-04 17:03:46,676] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:03:46,677] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-04 17:03:46,678] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 17:03:46,714] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-04 17:03:42.767246+00:00
[2022-12-04 17:03:46,726] {standard_task_runner.py:52} INFO - Started process 1218 to run task
[2022-12-04 17:03:46,731] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'manual__2022-12-04T17:03:42.767246+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpi0pngf2o', '--error-file', '/tmp/tmpf5ovkc10']
[2022-12-04 17:03:46,733] {standard_task_runner.py:80} INFO - Job 188: Subtask generate_two_int_task
[2022-12-04 17:03:46,822] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task manual__2022-12-04T17:03:42.767246+00:00 [running]> on host fb90b48d1471
[2022-12-04 17:03:46,934] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T17:03:42.767246+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-04T17:03:42.767246+00:00
[2022-12-04 17:03:46,955] {logging_mixin.py:115} INFO - /tmp/file.txt
[2022-12-04 17:03:46,956] {python.py:173} INFO - Done. Returned value was: None
[2022-12-04 17:03:46,978] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221204T170342, start_date=20221204T170346, end_date=20221204T170346
[2022-12-04 17:03:47,029] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-04 17:03:47,078] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
