[2022-12-11 16:39:12,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.wait_for_file manual__2022-12-11T16:39:04.244757+00:00 [queued]>
[2022-12-11 16:39:12,900] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.wait_for_file manual__2022-12-11T16:39:04.244757+00:00 [queued]>
[2022-12-11 16:39:12,901] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 16:39:12,903] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-11 16:39:12,903] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 16:39:12,922] {taskinstance.py:1377} INFO - Executing <Task(PythonSensor): wait_for_file> on 2022-12-11 16:39:04.244757+00:00
[2022-12-11 16:39:12,929] {standard_task_runner.py:52} INFO - Started process 3303 to run task
[2022-12-11 16:39:12,934] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'wait_for_file', 'manual__2022-12-11T16:39:04.244757+00:00', '--job-id', '1027', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpjq2vhnp4', '--error-file', '/tmp/tmpf8t5s742']
[2022-12-11 16:39:12,937] {standard_task_runner.py:80} INFO - Job 1027: Subtask wait_for_file
[2022-12-11 16:39:13,021] {task_command.py:369} INFO - Running <TaskInstance: first_dag.wait_for_file manual__2022-12-11T16:39:04.244757+00:00 [running]> on host 7e39590a7807
[2022-12-11 16:39:13,125] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=wait_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T16:39:04.244757+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-11T16:39:04.244757+00:00
[2022-12-11 16:39:13,129] {python.py:66} INFO - Poking callable: <function _wait_for_file at 0x7f6cec99f680>
[2022-12-11 16:39:13,149] {logging_mixin.py:115} INFO - _wait_for_file /tmp/file.txt
[2022-12-11 16:39:13,151] {base.py:301} INFO - Success criteria met. Exiting.
[2022-12-11 16:39:13,172] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=wait_for_file, execution_date=20221211T163904, start_date=20221211T163912, end_date=20221211T163913
[2022-12-11 16:39:13,237] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-11 16:39:13,289] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
