[2022-12-04 16:49:36,427] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:49:36,444] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:49:36,445] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:49:36,446] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-04 16:49:36,447] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:49:36,469] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_two_int_task> on 2022-12-03 00:00:00+00:00
[2022-12-04 16:49:36,477] {standard_task_runner.py:52} INFO - Started process 1025 to run task
[2022-12-04 16:49:36,487] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'generate_two_int_task', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpfntj8rya', '--error-file', '/tmp/tmp_cw1y7ed']
[2022-12-04 16:49:36,490] {standard_task_runner.py:80} INFO - Job 176: Subtask generate_two_int_task
[2022-12-04 16:49:36,580] {task_command.py:369} INFO - Running <TaskInstance: first_dag.generate_two_int_task scheduled__2022-12-03T00:00:00+00:00 [running]> on host fb90b48d1471
[2022-12-04 16:49:36,692] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=generate_two_int_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04 16:49:36,694] {python.py:173} INFO - Done. Returned value was: (992, 710)
[2022-12-04 16:49:36,737] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=generate_two_int_task, execution_date=20221203T000000, start_date=20221204T164936, end_date=20221204T164936
[2022-12-04 16:49:36,784] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-04 16:49:36,838] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
