[2022-12-04 15:59:03,201] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.hel1o scheduled__2022-02-04T00:00:00+00:00 [queued]>
[2022-12-04 15:59:03,259] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.hel1o scheduled__2022-02-04T00:00:00+00:00 [queued]>
[2022-12-04 15:59:03,260] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 15:59:03,261] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-04 15:59:03,262] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 15:59:03,296] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): hel1o> on 2022-02-04 00:00:00+00:00
[2022-12-04 15:59:03,339] {standard_task_runner.py:52} INFO - Started process 378 to run task
[2022-12-04 15:59:03,430] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'hel1o', 'scheduled__2022-02-04T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/first-dag.py', '--cfg-path', '/tmp/tmpliq7mpu1', '--error-file', '/tmp/tmpj4satyqn']
[2022-12-04 15:59:03,450] {standard_task_runner.py:80} INFO - Job 38: Subtask hel1o
[2022-12-04 15:59:04,277] {task_command.py:369} INFO - Running <TaskInstance: first_dag.hel1o scheduled__2022-02-04T00:00:00+00:00 [running]> on host fb90b48d1471
[2022-12-04 15:59:04,912] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=hel1o
AIRFLOW_CTX_EXECUTION_DATE=2022-02-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-04T00:00:00+00:00
[2022-12-04 15:59:04,917] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-04 15:59:04,919] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hello']
[2022-12-04 15:59:04,973] {subprocess.py:85} INFO - Output:
[2022-12-04 15:59:04,981] {subprocess.py:92} INFO - hello
[2022-12-04 15:59:04,983] {subprocess.py:96} INFO - Command exited with return code 0
[2022-12-04 15:59:05,326] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=hel1o, execution_date=20220204T000000, start_date=20221204T155903, end_date=20221204T155905
[2022-12-04 15:59:05,638] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-04 15:59:06,791] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
